version: '2'

services:
  myai.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  myai.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
